### PR TITLE
About screen

### PR DESCRIPTION
**Pull request by jesusrp98**
Adding updated about screen, with all details about this app.

### CODE REVIEW

**Comment by rodydavis** [comment]
OK I fixed the merge conflicts, I added our Personal Github Profiles and Twitters to the Url.dart if you want to add them the the about screen. I think i personally would like people to find me on twitter rather than Reddit, but what we could do is each have a List Tile with a trailing button bar will all out social icons.

**Comment by rodydavis** [comment]
We are so close! Still looking good for the weekend though!

**Review by rodydavis — APPROVED** [review]

**Comment by jesusrp98** [comment]
We could add them in the future. Want to do a exhaustive clean up & revise of the whole project before an official 1.0 update.
But want to launch the beta program asap, hopefully this weekend :)

**Comment by rodydavis** [comment]
Sounds good to me, i’m Ready to start on ios today, what do you need for google play? We probably want the same description and meta data. We also need screenshots for both. We’re you able to edit the icon at all with the project files i sent?

**Comment by jesusrp98** [comment]
Yep, icons are great. We could use the 'features' section I wrote in the readme, and add a couple more things.

**Comment by rodydavis** [comment]
Perfect!

Rody Davis Jr.
Full Stack Mobile Developer
Github | Website | Appstore | LinkedIn
Twitter | Facebook | YouTube

**Pull request merged**
