### PR TITLE
Adding Settings Page with Ability To Change Theme

### PR DESCRIPTION
**Pull request by rodydavis**
- Support for Sure Black Mode for OLED Screens
- Lost Custom Font (Temporarily)

### CODE REVIEW

**Comment by rodydavis** [comment]
Theme Ready to merge.

**Comment by rodydavis** [comment]
What colors do you want to have for the light theme?

also the space X pages has a local error on null. I just merged the latest from the master

**Comment by jesusrp98** [comment]
It's great that the theming aspect is nearly done!

About light theme's colors, I don't really mind right now, we could change them in the future. Leave the stock ones for now, it's OK.
 
If you could tell me where did you find the error, I couldn't find anything wrong.

And finally, I wanted to know how could we implement a dynamic system to change the accent & text colors when changing theme, avoiding using the `colors.dart` file.

**Comment by jesusrp98** [comment]
And what about fonts? Are they hard to implement in the new theme system?

**Comment by rodydavis** [comment]
Working on the fonts still.

And I was only using the colors.dart because I thought you had a preference for it. I can remove it and fully customize.

**Comment by jesusrp98** [comment]
So one option could be having predefined colors for both themes on a single file, like we have right now with the `colors.dart` file. But, I think it would be great picking the standard text colors for each brightness. That'd mean having only primary & accent colors on the `colors.dart` for both themes.

**Comment by rodydavis** [comment]
I like that, I’ll update accordingly!

**Comment by jesusrp98** [comment]
Great!

**Comment by jesusrp98** [comment]
Custom fonts are now fixed.
Other improvements also have been made.

**Pull request merged**
